Stories/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserStories.Logging;
using UserStories.Models;
using System.Reflection;
using Stories.BLL.Models;
using System.IO;

namespace UserStories.Controllers
{

    [Authorize]
    public class StoriesController : BaseController
    {
        int BlockSize = 25;
        public ActionResult Index()
        {
            LogHelper.WriteDebug(MethodBase.GetCurrentMethod(), "Start StoriesController.Index()");

            var stories = _BusinessManager.GetAllStories(1, BlockSize);

            return View(stories);
        }

        public ActionResult Details(int id)
        {
            var model = _BusinessManager.GetStory(id);

            var group = _BusinessManager.GetAllGroups().Where(g => g.Id == model.StoryGroupId).FirstOrDefault();

            if (group != null)
            {
                ViewData["GroupName"] = group.Name;
            }

            return View(ModelAdapter.StoryAdaptation(model));
        }

        public ActionResult Edit(int id)
        {
            var model = _BusinessManager.GetStory(id);

            ViewData["Groups"] = _BusinessManager.GetAllGroups();

            return View(ModelAdapter.StoryAdaptation(model));
        }

        [HttpPost]
        public ActionResult Edit(StoryModel model)
        {
            return RedirectToAction("Index");
        }
            

        public ActionResult NewStory()
        {
            LogHelper.WriteDebug(MethodBase.GetCurrentMethod(), "Start StoriesController.NewStory()");

            ViewData["Groups"] = _BusinessManager.GetAllGroups();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewStory(StoryModel model)
        {
            LogHelper.WriteDebug(MethodBase.GetCurrentMethod(), "Start StoriesController.NewStory()");

            ViewData["Groups"] = _BusinessManager.GetAllGroups();

            if (ModelState.IsValid)
            {
                foreach (var groupId in model.GroupIds)
                {
                    var story = new StoryBM()
                    {
                        UserId = UserId,
                        Title = model.Title,
                        Description = model.Description,
                        Content = model.Content,
                        PostedOn = DateTime.Now,
                        StoryGroupId = groupId
                    };

                    _BusinessManager.AddStory(story);
                }

                return RedirectToAction("Index", new { succeed = true });
            }

            return View(model);
        }


        public ActionResult StoryList(List<StoryBM> Model)
        {
            LogHelper.WriteDebug(MethodBase.GetCurrentMethod(), "Start StoriesController.NewStory()");
            return PartialView(Model);
        }

        [HttpPost]
        public ActionResult InfinateScroll(int BlockNumber)
        {
            LogHelper.WriteDebug(MethodBase.GetCurrentMethod(), "Start StoriesController.InfinateScroll()");

            var stories = _BusinessManager.GetAllStories(BlockNumber, BlockSize);

            JsonStoryModel jsonModel = new JsonStoryModel();
            jsonModel.NoMoreData = stories.Count < BlockSize;
            jsonModel.HTMLString = RenderPartialViewToString("StoryList", stories);

            return Json(jsonModel);
        }

        protected string RenderPartialViewToString(string viewName, object model)
        {
            LogHelper.WriteDebug(MethodBase.GetCurrentMethod(), "Start StoriesController.RenderPartialViewToString()");

            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;

            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }

    }
}

Stories/Views/Stories/Details.cshtml
@model UserStories.Models.StoryModel
@{
    ViewBag.Title = "New Story";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Details</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">                                    
                                    @Html.Label(@Model.Title, new { @class = "control-label col-sm-2" })
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.Label(@Model.Description, new { @class = "control-label col-sm-2" })                                 
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.Label(@Model.Content, new { @class = "control-label col-sm-2" })                                 
                                </div>
                            </div>  
                            
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Group(s)</label>
                                <div class="col-sm-10">
                                    @Html.Label(ViewData["GroupName"].ToString(), new { @class = "control-label col-sm-2" })
                                </div>
                            </div>      
                                                 
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a class="btn btn-white" href="/Stories">Cancel</a>                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Stories/Views/Stories/Edit.cshtml
@model UserStories.Models.StoryModel
@{
    ViewBag.Title = "New Story";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Edit Story <small>edit story section</small></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Title, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Title)
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.TextAreaFor(model => model.Content, 5, 20, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Content)
                                </div>
                            </div>     
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Group(s)</label>
                                <div class="col-sm-10">
                                    <div class="col-lg-4 m-l-n">
                                        @Html.DropDownList("GroupIds", new SelectList((System.Collections.IEnumerable)ViewData["Groups"], "Id", "Name", @Model.GroupIds.FirstOrDefault()), new { @class = "form-control", @multiple = "" })
                                    </div>
                                </div>
                            </div>                      
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a class="btn btn-white" href="/Stories">Cancel</a>                                    
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Stories/Views/Stories/Index.cshtml
@model List<Stories.BLL.Models.StoryBM>

@{
    ViewBag.Title = "My Stories";
}
<script src="@Url.Content("~/Scripts/jquery-2.1.1.min.js")" type="text/javascript"></script>
<div class="wrapper wrapper-content animated fadeInRight">
    <section id="features" class="container services">
       @{Html.RenderAction("StoryList", "Stories", new { Model = Model });}
    </section>
</div>

<script type="text/javascript">
    var BlockNumber = 2;  //Infinate Scroll starts from second block
    var NoMoreData = false;
    var inProgress = false;

    $(document).ready(function () {
        $(window).scroll(function () {

          
            if ($(window).scrollTop() >= $(document).height() - $(window).height() - 5 && !NoMoreData && !inProgress) {

                inProgress = true;
                $("#loadingDiv").show();

                $.post("@Url.Action("InfinateScroll", "Stories")", { "BlockNumber": BlockNumber },
                    function (data) {

                        BlockNumber = BlockNumber + 1;
                        NoMoreData = data.NoMoreData;
                        $("#rowDiv").append(data.HTMLString);
                        $("#loadingDiv").hide();
                        inProgress = false;
                    });
            }
        });
    });
</script>

Stories/Views/Stories/NewStory.cshtml
@model UserStories.Models.StoryModel
@{
    ViewBag.Title = "New Story";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>New Story <small>Add new story section</small></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Title, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Title)
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.TextAreaFor(model => model.Content, 5, 20, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Content)
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Group(s)</label>
                                <div class="col-sm-10">
                                    <div class="col-lg-4 m-l-n">
                                        @Html.DropDownList("GroupIds", new SelectList((System.Collections.IEnumerable)ViewData["Groups"], "Id", "Name"), new { @class = "form-control", @multiple = "" })
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="submit">Cancel</button>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Stories/Views/Stories/StoryList.cshtml
@model List<Stories.BLL.Models.StoryBM>

<div class="row" id="rowDiv">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="col-sm-3">
            <h2>@Model[@i].Title</h2>
            <p>@Model[@i].Description</p>
            <p>
                <a class="navy-link" href="/Stories/Details/@Model[@i].Id" role="button">Details &raquo;</a></p>
            <p><a class="navy-link" href="/Stories/Edit/@Model[@i].Id" role="button">Edit &raquo;</a></p>
        </div>
    }

</div>